input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = compose:caps
    kb_rules =

    numlock_by_default = true
    repeat_rate = 30
    repeat_delay = 300

    follow_mouse = 1
    sensitivity = -0.34
    accel_profile = flat
}