# Themes
source = ~/.config/matugen/generated/hyprland-colors.conf
exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
env = GTK_THEME,Adwaita-dark
env = QT_QPA_PLATFORMTHEME,qt5ct
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
env = XCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
exec = hyprctl setcursor Bibata-Modern-Ice 32

xwayland {
    force_zero_scaling = true
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = $primary
    col.inactive_border = $inverse_on_surface
    resize_on_border = false
    
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.35

    shadow {
        enabled = false
        range = 35
        render_power = 2 #(values betwwen 1 and 4, no higher than 4, cuz invalid)
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = false
        size = 4                # Radius
        passes = 2              # Quality (2 is a good balance of perf/looks)
        new_optimizations = true
        ignore_opacity = true   # Blurs behind transparent windows even if opacity is high
        xray = false            # If true, you can "see through" the blur.
        vibrancy = 0.1696
    }
}

misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}