# Secondary, vertical & to the left
monitorv2 {
	output = DP-2
	mode = 3840x2160@60
	position = -1152x-445
	scale = 1.875
	transform = 1
}

# Main, horizontal & to the right
monitorv2 {
	output = DP-1
	mode = 2560x1440@144
	position = 0x0
	scale = 1.25
	transform = 0
}